finished add message application business rules and changed user to username
meldy04/virtual-bookclub pull request #20
Opened 2024-11-20 22:40 UTC by zeitoun1

finished add message application business rules and changed user to username.

2024-11-23 17:58 UTC, meldy04 requested changes
Overall great changes, just a couple of tweaks.

2024-11-23 17:58 UTC, meldy04 commented on src/main/java/use_case/add_message/AddMessageInteractor.java
addMessageDataAccessInterface and addMessageOutputBoundary have not been assigned values. Could we add a constructor?

public AddMessageInteractor(AddMessageDataAccessInterface dataAccess, AddMessageOutputBoundary outputBoundary) {
        this.addMessageDataAccessInterface = dataAccess;
        this.addMessageOutputBoundary = outputBoundary;
    }

2024-11-23 17:58 UTC, meldy04 commented on src/test/java/use_case/join_club/JoinClubInteractorTest.java
Could we extract method returning 'joinClubInteractor' from surrounding method to reduce complexity? (SRP + OCP)

2024-11-23 18:02 UTC, zeitoun1 commented on src/main/java/use_case/add_message/AddMessageInteractor.java
ye my bad will add the constructor in the next commit

2024-11-23 18:05 UTC, zeitoun1 commented on src/test/java/use_case/join_club/JoinClubInteractorTest.java
I'm not sure which method you mean, can you give me the line number.

2024-11-23 18:08 UTC, meldy04 commented on src/test/java/use_case/join_club/JoinClubInteractorTest.java
Lines 23 and 49

2024-11-23 18:17 UTC, zeitoun1 commented on src/test/java/use_case/join_club/JoinClubInteractorTest.java
Oh I get what you mean, In this line, it's creating an anonymous class implementation. i think extracting the code somewhere in the test would create ambiguity as whoever is reading the test would have to go back to the extracted method to understand the new behaviour of the presenter.  Not sure how it would affect SRP or OCP though. There is a way to remove the error by not suggesting extraction on a method as short as this, I guess that is what the instructors used in the lab 5 tests.

2024-11-23 18:20 UTC, meldy04 commented on src/test/java/use_case/join_club/JoinClubInteractorTest.java
Okay, perfect! No worries.

2024-11-23 18:20 UTC, meldy04 approved these changes

2024-11-25 00:30 UTC, jason101111 approved these changes

2024-11-25 02:04 UTC, merged